### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lukasbystricky** [Kurtsley/henry-blake-fuller_bertram-copes-year#1]
Very good work! There's just a few minor issues.

- [x] You'll need to add a [lint ignore file ](https://standardebooks.org/manual/1.8.0/single-page#2.3)
- [x] 64b4789: I don't necessarily disagree, but do you know if this change has been made in more recent additions? Also, are you sure the change couldn't be from "we" to "me"? That seems like a more likely error for a printer to make. 
- [x] 1a49c2d: I think you can keep the capitals on Eminent and Queer, it looks to me like those are being used as proper nouns. Possibly the same is true with d02b698. 
- [x] Some of the italics you removed should be kept. I didn't got through all of them, but some I see are:
- "rus in urbe" ("[rus in urbe](https://www.merriam-webster.com/dictionary/rus%20in%20urbe)" is in MW, but it's specifically identified as a Latin phrase)
- "in vacuo" (This is covered by rule [8.2.9.9](https://standardebooks.org/manual/1.8.0/single-page#8.2.9.9))
- "abat-jour" (This is also [in MW](https://www.merriam-webster.com/dictionary/abat-jour), but it's only in the unabridged edition)
- [x] There are some issues with the letter formatting:
- In chapter-7, shouldn't this be two separate letters? 
- In chapter-12, I don't think the first and fourth letter should be stylized at all. Those are inline quotations, not really block quotations. Same goes for one of the letters in chapter-20.
-  Also in chapter-12, the footer on the last letter should be inside the blockquote
- The signatures in chapter-12 and in chapter-7 should be given the personal-name semantic instead of given-name

**Comment by Kurtsley** [comment]
I checked the scans and saw that you were correct about the printing error. That has been changed to "me" instead of "us." I added italics as it appears that way in the scans.

The capitalization has been restored and most of the italics as well. Only the very common words like fiancé have been left alone.

I struggled with the  letters in this production, I wasn't sure if they really qualified as letters at all. If the text contains an inline quotations then it shouldn't be styled as a letter? That makes this last part of the chapter 12 letter a bit confusing.

“Look about a bit for quarters,” Lemoyne went on, drawing toward his conclusion. “I presume room-rent is little more for two than for one. Possibly,” he put down in an afterthought, “I might get a job in the city;” and then, “with warm regards,” he came to a close as “Art.”

Should this be styled as a letter as well? You mentioned that this should be in a footer in the blockquote, but i assume that would only apply if it *is* styled. Should this section have valediction and signature semantics even if not styled as a letter?

**Comment by lukasbystricky** [comment]
I misread the letter in chapter 12. No need to put that as a footer. I think the letters in this production were rather tricky. In general though, unless they actually are blockquotes you shouldn't put them in blockquote tags. What you can do is to put the quotes from letters inside spans and tag them with the z3998:letter semantics. Likewise you can tag "Art" with the appropriate semantics, probably "z3998:sender z3988:signature" inside a span. 

I should have mentioned this in the original review, but the rule for when to apply italics to foreign words is given in [8.2.9.4](https://standardebooks.org/manual/1.8.0/single-page#8.2.9.4). I see you added back the italics to some words where you were correctly removed them the first time, e.g. "à deux". When searching on MW, make sure it's in the basic search results, and not the unabridged.

**Comment by Kurtsley** [comment]
I did see that "basic online search" rule, but I have no idea how to tell if it the unabridged results. I'm not using the paid version of MW, just the regular site.

**Comment by lukasbystricky** [comment]
It's maybe not obvious, but if you scroll down the page if a word isn't in
the abridged dictionary there will be a box with the title 'Love words?"
which will give you you information about which dictionary it's in. See
here for example: https://www.merriam-webster.com/dictionary/abat-jou

If the box doesn't show up, or it doesn't say anything about a different
dictionary it's in the abridged dictionary.

**Comment by Kurtsley** [comment]
I see it now, thanks for that. I think I finally have the correct language italics.

I've cleaned up the chapter 12 land 20 letters. I'm not sure I formatted the spans correctly. I put the z3998:letter semantics in each individual span, including the valediction and signature spans.

It looks strange to have parts of the letter as blocks and part inline, this can't be very common.

**Comment by Kurtsley** [comment]
I took the liberty to add some local CSS rules to make the valediction and signature appear as normal text in the inline letter. The linter does not like that, it wants the signature to have small-caps or italics. Do you think I should add this to the lint-ignore or re-apply the small-caps font variant?

**Comment by lukasbystricky** [comment]
Yeah it's a bit uncommon, but it's not unheard of. See [here](https://github.com/search?q=owner%3Astandardebooks+path%3Asrc%2Fepub%2Ftext%2F*.xhtml+%22%3Cspan+epub%3Atype%3D%5C%22z3998%3Aletter%22&type=code) for some examples. You can add a lint ignore there if you think the small-caps look out of place.

**Comment by Kurtsley** [comment]
While I didn't see any exact examples of what is going on in chapter 12, I think it is correct. The valediction and sender/signature spans in this case are separated by narrative sections, so the z3998:letter tag must be applied to each span.

If that looks good, this should be ready.

**Comment by lukasbystricky** [comment]
Looks good to me. I'll pass it off to Alex.
